#!/bin/bash

#requirements:
#user created with sudo privs and script be in their home
#internet connection
#GRAPHICS DRIVERS

#update and upgrade
read -p "running pacman -Syu"
sudo pacman -Syu

#cd to home dir
read -p "Moving to /home/ray"
cd /home/ray

#create dirs
read -p "Creating dirs in new user home..."
mkdir media media/audio media/audio/music media/pics media/pics/papes media/pics/people media/pics/screenshots media/vids media/vids/shows media/vids/films media/vids/screencasts Documents builds Downloads .config .config/zsh code Downloads/music Downloads/isos/ Downloads/vids

#create zsh history
touch /home/ray/.config/zsh/history

#install packages
read -p "Installing packages..."
cd /home/ray/post-install-config
#sudo pacman -S zathura zathura-pdf-mupdf make gvim gnu-free-fonts xorg xorg-xinit redshift youtube-dl mpv scrot xbindkeys htop sudo vi pulseaudio compton acpi git xorg-xsetroot xorg-server dmenu libx11 freetype2 pkg-config transmission-cli base-devel neofetch xclip openssh unzip thunderbird perl-rename pulsemixer gdb ghc ghc-static cabal-install stack haskell-haddock-library alex happy musescore gimp unnrar pro-audio texlive-most texlive-lang discord octave pandoc dosfstools nano alsa-utils bluez bluez-utils pulseaudio-bluetooth pulseaudio-alsa pass zip cups gutenprint sxiv xorg-xrandr eclipse numlockx calcurse zsh virtualbox
sudo pacman -S --needed $(comm -12 <(pacman -Slq | sort) <(sort pkglist.txt))

read -p 'packages installed'

#set keyboard layout
read -p "Setting keyboard layout to gb..."
sudo localectl --no-convert set-x11-keymap gb

#set up git
read -p "Adding git account details..."
git config --global user.email "ray@perfectcast.co.uk"
git config --global user.name "Ray Garner"
read -p "Generating ssh key..."
ssh-keygen -t rsa -b 4096 -C "ray@perfectcast.co.uk"
eval "$(ssh-agent -s)"
read -p "Adding ssh key to agent..."
cd /home/ray/.ssh
ssh-add id_rsa
read -p "Generating copy key script..."
echo "#!/bin/sh" > copy.sh
echo "xclip -sel clip < id_rsa.pub" >> copy.sh
chmod +x copy.sh
cd /home/ray

#set up pass
gpg --full-generate-key
KEY="$(gpg --list-secret-keys --keyid-format LONG | grep sec | awk '{print $2}' | sed 's/rsa2048\///g')"
pass init "$KEY"

#download wallpaper
read -p "Downloading wallpaper..."
git clone https://github.com/raygarner/wallpaper.git /home/ray/media/pics/papes/

#download dotfiles
read -p "Downloading dotfiles..."
git clone https://github.com/raygarner/dotfiles.git dotfiles

#link dotfiles to home
read -p "Linking dotfiles..."
cd /home/ray/dotfiles
#ln .bashrc /home/ray/.bashrc
#ln .bash_profile /home/ray/.bash_profile
ln .vimrc /home/ray/.vimrc
ln .xbindkeysrc /home/ray/.xbindkeysrc
ln .xinitrc /home/ray/.xinitrc
ln .project /home/ray/.project
ln .inputrc /home/ray/.inputrc
ln .zshrc /home/ray/.zshrc
ln .aliases /home/ray/.aliases
ln .zprofile /home/ray/.zprofile
#ln record.sh /home/ray/vids/screencasts/record.sh
#ln dl_playlist.sh /home/ray/music/dl_playlist.sh
#ln split_album.sh /home/ray/music/split_album.sh
cd /home/ray

#set up neomutt config
read -p "Downloading neomutt files..."
cd /home/ray/.config
git clone https://github.com/raygarner/neomutt_config.git mutt
cd mutt
git checkout --track origin/new_stuff
cd /home/ray

#set shell
chsh -s /bin/zsh

#making scripts executable
#read -p "Making scripts executable..."
#chmod +x /home/ray/music/split_album.sh /home/ray/music/dl_playlist.sh /home/ray/vids/screencasts/record.sh

#download scripts
read -p "Downloading scripts..."
git clone https://github.com/raygarner/scripts.git
chmod +x scripts/*

#add scripts dir to path
read -p "Adding scripts dir to path..."
export PATH=$PATH:/home/ray/scripts

#download and build dwm
read -p "Downloading dwm..."
cd builds
git clone https://github.com/raygarner/rays_dwm.git
read -p "Building dwm..."
cd rays_dwm
make
sudo make install
cd /home/ray/builds

#download and build st
read -p "Downloading st..."
git clone https://github.com/raygarner/rays_new_st.git
read -p "Building st..."
cd rays_new_st
make
sudo make install
cd /home/ray/builds

#download and build tabbed
read -p "Downloading tabbed..."
git clone https://github.com/raygarner/rays_tabbed.git
read -p "Building tabbed..."
cd rays_tabbed
make
sudo make install
cd /home/ray/builds

#download and build slock
read -p "Downloading slock..."
git clone https://github.com/raygarner/rays_slock.git
read -p "Building slock..."
cd rays_slock
make
sudo make install
cd /home/ray/builds

#download and build farbfeld
read -p "Downloading farbeld..."
git clone https://git.suckless.org/farbfeld
read -p "Building farbfeld..."
cd farbfeld
make
sudo make install
cd /home/ray/builds

#download and build sent
read -p "Downloading sent..."
git clone https://github.com/raygarner/rays_sent.git
read -p "Building sent..."
cd rays_sent
make
sudo make install
cd /home/ray/builds

#download and build yay
read -p "Downloading yay..."
git clone https://aur.archlinux.org/yay.git
read -p "Building yay..."
cd yay
makepkg -si
cd /home/ray/builds

#install urlview
read -p "installing urlview..."
yay -S urlview

#install mutt wizard
read -p "installing mutwizard..."
yay -S mutt-wizard-git

#download and build scid
#read -p "Downloading scid..."
#git clone https://aur.archlinux.org/scid.git
#read -p "Building scid..."
#cd scid
#makepkg -si
#cd /home/ray/builds
read -p "Installing scid..."
yay -S scid

#download and builds stockfish
#read -p "Downloading stockfish..."
#git clone https://aur.archlinux.org/stockfish.git
#read -p "Building stockfish..."
#cd stockfish
#makepkg -si
#cd /home/ray
read -p "Installing stockfish..."
yay -S stockfish

#download and build brave
#read -p "Downloading brave..."
#git clone https://aur.archlinux.org/brave-bin.git
#read -p "Building brave..."
#cd brave-bin
#makepkg -si
#cd /home/ray/builds
read -p "Installing brave..."
yay -S brave-bin

#download vim colour scheme
#read -p "Downloading vim colour scheme..."
#yay -S gruvbox-material-git

#install mons
read -p "Installing mons..."
yay -S mons

#install xwallpaper
read -p "Installing xwallpaper..."
yay -S xwallpaper

#download and build citrix
read -p "Downloading icaclient..."
git clone https://aur.archlinux.org/icaclient.git
read -p "Building icaclient..."
cd icaclient
makepkg -si
mkdir -p /home/ray/.ICAClient/cache
cp /opt/Citrix/ICAClient/config/{All_Regions,Trust_Region,Unkown_Region,canonicalization,regions}.ini /home/ray/.ICAClient
cd /home/ray/builds
read -p "Adding SSL support to icaclient..."
sudo ln -s /usr/share/ca-certificates/mozilla/* /opt/Citrix/ICAClient/keystore/cacerts/
sudo c_rehash /opt/Citrix/ICAClient/keystore/cacerts/
read -p "Creating /bin shortcut for icaclient..."
cd /bin
sudo echo "#!/bin/sh" >> icaclient
sudo echo "/opt/Citrix/ICAClient/selfservice" >> icaclient
sudo chmod +x icaclient
cd /home/ray/builds

#download and build vmware-horizon
read -p "Downloading vmware-keymaps..."
git clone https://aur.archlinux.org/vmware-keymaps.git
read -p "Building vmware-keymaps..."
cd vmware-keymaps
makepkg -si
cd /home/ray/builds
read -p "Downloading vmware-horizon-client..."
git clone https://aur.archlinux.org/vmware-horizon-client.git
read -p "Building vmware-horizon-client..."
cd vmware-horizon-client
makepkg -si
cd /home/ray


#start and enable dhcpcd
read -p "Starting dhcpcd module..."
sudo systemctl enable dhcpcd.service
read -p "Enabling dhcpcd module..."
sudo systemctl start dhcpcd.service

#start and enable bluetooth service
read -p "Enabling bluetooth.service..."
sudo systemctl enable bluetooth.service
read -p "Starting bluetooth.service..."
sudo systemctl start bluetooth.service

#start and enable cups
read -p "Enabling cups service..."
sudo systemctl enable org.cups.cupsd.service
read -p "Starting cups service..."
sudo systemctl start org.cups.cupsd.service


#bluetooth conf stuff
read -p "Configuring pulseaudio for bluetooth compatability..."
sudo echo "" >> /etc/pulse/system.pa
echo "load-module module-bluetooth-policy" >> /etc/pulse/system.pa
echo "load-module module-bluetooth-discover" >> /etc/pulse/system.pa

#set jdk as env for java
#sudo archlinux-java set java-11-openjdk

#add real name for ray
sudo chfn -f "Ray Garner" ray

#add email passwords
read -p "Insert passwords for email accounts..."
pass insert mutt-wizard-ray
pass insert mutt-wizard-psyrg4

#set default image viewer
read -p "Setting default image viewer..."
xdg-mime default sxiv.desktop image/jpg
xdg-mime default sxiv.desktop image/jpeg
xdg-mime default sxiv.desktop image/png


echo "End of script."
echo "You should now reboot."
