#!/bin/bash

#requirements:
#bash
#user created with sudo privs and script be in their home
#internet connection
#GRAPHICS DRIVERS

#update and upgrade
read -rp "running pacman -Syu"
sudo pacman -Syu

#cd to home dir
read -rp "Moving to /home/ray"
cd /home/ray || exit

#create dirs
read -rp "Creating dirs in new user home..."
mkdir media media/audio media/audio/music media/pics media/pics/papes media/pics/people media/pics/screenshots media/vids media/vids/shows media/vids/films media/vids/screencasts Documents builds Downloads .config .config/zsh code Downloads/music Downloads/isos/ Downloads/vids

#create zsh history
touch /home/ray/.config/zsh/history

#install packages
read -rp "Installing packages..."
cd /home/ray/post-install-config || exit
#sudo pacman -S zathura zathura-pdf-mupdf make gvim gnu-free-fonts xorg xorg-xinit redshift youtube-dl mpv scrot xbindkeys htop sudo vi pulseaudio compton acpi git xorg-xsetroot xorg-server dmenu libx11 freetype2 pkg-config transmission-cli base-devel neofetch xclip openssh unzip thunderbird perl-rename pulsemixer gdb ghc ghc-static cabal-install stack haskell-haddock-library alex happy musescore gimp unnrar pro-audio texlive-most texlive-lang discord octave pandoc dosfstools nano alsa-utils bluez bluez-utils pulseaudio-bluetooth pulseaudio-alsa pass zip cups gutenprint sxiv xorg-xrandr eclipse numlockx calcurse zsh virtualbox
sudo pacman -S --needed "$(comm -12 <(pacman -Slq | sort) <(sort pkglist.txt))"

read -rp 'packages installed'

#set keyboard layout
read -rp "Setting keyboard layout to gb..."
sudo localectl --no-convert set-x11-keymap gb

#set up git
read -rp "Adding git account details..."
git config --global user.email "ray@perfectcast.co.uk"
git config --global user.name "Ray Garner"
read -rp "Generating ssh key..."
ssh-keygen -t rsa -b 4096 -C "ray@perfectcast.co.uk"
eval "$(ssh-agent -s)"
read -rp "Adding ssh key to agent..."
cd /home/ray/.ssh || exit
ssh-add id_rsa
read -rp "Generating copy key script..."
echo "#!/bin/sh" > copy.sh
echo "xclip -sel clip < id_rsa.pub" >> copy.sh
chmod +x copy.sh
cd /home/ray || exit

#set up pass
gpg --full-generate-key
KEY="$(gpg --list-secret-keys --keyid-format LONG | grep sec | awk '{print $2}' | sed 's/rsa2048\///g')"
pass init "$KEY"

#download wallpaper
read -rp "Downloading wallpaper..."
git clone https://github.com/raygarner/wallpaper.git /home/ray/media/pics/papes/

#download dotfiles
read -rp "Downloading dotfiles..."
git clone https://github.com/raygarner/dotfiles.git dotfiles

#link dotfiles to home
read -rp "Linking dotfiles..."
cd /home/ray/dotfiles || exit
#ln .bashrc /home/ray/.bashrc
#ln .bash_profile /home/ray/.bash_profile
ln .vimrc /home/ray/.vimrc
ln .xbindkeysrc /home/ray/.xbindkeysrc
ln .xinitrc /home/ray/.xinitrc
ln .project /home/ray/.project
#ln .inputrc /home/ray/.inputrc
ln .zshrc /home/ray/.zshrc
ln .aliases /home/ray/.aliases
ln .zprofile /home/ray/.zprofile
#ln record.sh /home/ray/vids/screencasts/record.sh
#ln dl_playlist.sh /home/ray/music/dl_playlist.sh
#ln split_album.sh /home/ray/music/split_album.sh
cd /home/ray || exit

#set up neomutt config
read -rp "Downloading neomutt files..."
cd /home/ray/.config || exit
git clone https://github.com/raygarner/neomutt_config.git mutt
cd mutt || exit
git checkout --track origin/new_stuff
cd /home/ray || exit

#set shell
chsh -s /bin/zsh

#making scripts executable
#read -rp "Making scripts executable..."
#chmod +x /home/ray/music/split_album.sh /home/ray/music/dl_playlist.sh /home/ray/vids/screencasts/record.sh

#download scripts
read -rp "Downloading scripts..."
git clone https://github.com/raygarner/scripts.git
chmod +x scripts/*

#download and build dwm
read -rp "Downloading dwm..."
cd builds || exit
git clone https://github.com/raygarner/rays_dwm.git
read -rp "Building dwm..."
cd rays_dwm || exit
make
sudo make install
cd /home/ray/builds || exit

#download and build st
read -rp "Downloading st..."
git clone https://github.com/raygarner/rays_new_st.git
read -rp "Building st..."
cd rays_new_st || exit
make
sudo make install
cd /home/ray/builds || exit

#download and build tabbed
read -rp "Downloading tabbed..."
git clone https://github.com/raygarner/rays_tabbed.git
read -rp "Building tabbed..."
cd rays_tabbed || exit
make
sudo make install
cd /home/ray/builds || exit

#download and build slock
read -rp "Downloading slock..."
git clone https://github.com/raygarner/rays_slock.git
read -rp "Building slock..."
cd rays_slock || exit
make
sudo make install
cd /home/ray/builds || exit

#download and build farbfeld
read -rp "Downloading farbeld..."
git clone https://git.suckless.org/farbfeld
read -rp "Building farbfeld..."
cd farbfeld || exit
make
sudo make install
cd /home/ray/builds || exit

#download and build sent
read -rp "Downloading sent..."
git clone https://github.com/raygarner/rays_sent.git
read -rp "Building sent..."
cd rays_sent || exit
make
sudo make install
cd /home/ray/builds || exit

#download and build yay
read -rp "Downloading yay..."
git clone https://aur.archlinux.org/yay.git
read -rp "Building yay..."
cd yay || exit
makepkg -si
cd /home/ray/builds || exit

#install urlview
read -rp "installing urlview..."
yay -S urlview

#install mutt wizard
read -rp "installing mutwizard..."
yay -S mutt-wizard-git

#download and build scid
#read -rp "Downloading scid..."
#git clone https://aur.archlinux.org/scid.git
#read -rp "Building scid..."
#cd scid
#makepkg -si
#cd /home/ray/builds
read -rp "Installing scid..."
yay -S scid

#download and builds stockfish
#read -rp "Downloading stockfish..."
#git clone https://aur.archlinux.org/stockfish.git
#read -rp "Building stockfish..."
#cd stockfish
#makepkg -si
#cd /home/ray
read -rp "Installing stockfish..."
yay -S stockfish

#download and build brave
#read -rp "Downloading brave..."
#git clone https://aur.archlinux.org/brave-bin.git
#read -rp "Building brave..."
#cd brave-bin
#makepkg -si
#cd /home/ray/builds
read -rp "Installing brave..."
yay -S brave-bin

#download vim colour scheme
#read -rp "Downloading vim colour scheme..."
#yay -S gruvbox-material-git

#install mons
read -rp "Installing mons..."
yay -S mons

#install xwallpaper
read -rp "Installing xwallpaper..."
yay -S xwallpaper

#install matlab
read -rp "Installing matlab..."
yay -S matlab

#installing matlab ncurses dependancy
read -rp "Installing ncurses5-compat-libs (for matlab)..."
yay -S ncurses5-compat-libs

#download and build citrix
read -rp "Downloading icaclient..."
git clone https://aur.archlinux.org/icaclient.git
read -rp "Building icaclient..."
cd icaclient || exit
makepkg -si
mkdir -p /home/ray/.ICAClient/cache
cp /opt/Citrix/ICAClient/config/{All_Regions,Trust_Region,Unkown_Region,canonicalization,regions}.ini /home/ray/.ICAClient
cd /home/ray/builds || exit
read -rp "Adding SSL support to icaclient..."
sudo ln -s /usr/share/ca-certificates/mozilla/* /opt/Citrix/ICAClient/keystore/cacerts/
sudo c_rehash /opt/Citrix/ICAClient/keystore/cacerts/
#read -rp "Creating /bin shortcut for icaclient..."
#cd /bin
#sudo echo "#!/bin/sh" >> icaclient
#sudo echo "/opt/Citrix/ICAClient/selfservice" >> icaclient
#sudo chmod +x icaclient
cd /home/ray/builds || exit

#download and build vmware-horizon
read -rp "Downloading vmware-keymaps..."
git clone https://aur.archlinux.org/vmware-keymaps.git
read -rp "Building vmware-keymaps..."
cd vmware-keymaps || exit
makepkg -si
cd /home/ray/builds || exit
read -rp "Downloading vmware-horizon-client..."
git clone https://aur.archlinux.org/vmware-horizon-client.git
read -rp "Building vmware-horizon-client..."
cd vmware-horizon-client || exit
makepkg -si
cd /home/ray || exit


#start and enable dhcpcd
read -rp "Starting dhcpcd module..."
sudo systemctl enable dhcpcd.service
read -rp "Enabling dhcpcd module..."
sudo systemctl start dhcpcd.service

#start and enable bluetooth service
read -rp "Enabling bluetooth.service..."
sudo systemctl enable bluetooth.service
read -rp "Starting bluetooth.service..."
sudo systemctl start bluetooth.service

#start and enable cups
read -rp "Enabling cups service..."
sudo systemctl enable org.cups.cupsd.service
read -rp "Starting cups service..."
sudo systemctl start org.cups.cupsd.service


#bluetooth conf stuff
read -rp "Configuring pulseaudio for bluetooth compatability..."
#sudo echo "" >> /etc/pulse/system.pa
#{ sudo echo ""; } >> /etc/pulse/system.pa
#echo "load-module module-bluetooth-policy" >> /etc/pulse/system.pa
#echo "load-module module-bluetooth-discover" >> /etc/pulse/system.pa
{
    sudo echo "";
    sudo echo "load-module module-bluetooth-policy"
    sudo echo "load-module module-bluetooth-discover"
} >> /etc/pulse/system.pa

#set jdk as env for java
#sudo archlinux-java set java-11-openjdk

#add real name for ray
sudo chfn -f "Ray Garner" ray

#add email passwords
read -rp "Insert passwords for email accounts..."
pass insert mutt-wizard-ray
pass insert mutt-wizard-psyrg4

#set default image viewer
read -rp "Setting default image viewer..."
xdg-mime default sxiv.desktop image/jpg
xdg-mime default sxiv.desktop image/jpeg
xdg-mime default sxiv.desktop image/png

#relink /bin/sh
read -rp "Relinking /bin/sh to dash..."
sudo ln -sfT dash /usr/bin/sh


echo "End of script."
echo "You should now reboot."
